-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgda0zdMwDNB2Fbr5k
ETpKnL2xr9aFtkUT8zxB1wWkzGSgCgYIKoZIzj0DAQehRANCAAQOPjglQcENX10h
KVH8KUcy76tKUyyfDnaPHKsWNj5ua7h6eQjnFJ+lWcGlYywdZPlXneKUMwro8VIT
7HbGnpAB
-----END PRIVATE KEY-----